### ISSUE TITLE
Code completion - Cursor at end of line should allow code completion

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#253]
So you can position the cursor at the end of the line and still press ctrl + space to get the list of options to insert, and then the plugin automatic adds the `&` or `&amp;` so you dont have to do that yourself. This was how it was working before as well.

```
        from("timer:trigger?daemon=false&fixedRate=true<caret>")
                .transform().simple("ref:myBean")
                .to("log:out");
```

If you press `cltr + space` at the `<caret>` then it should show the options and then append it correctly.

**Comment by fharms** [comment]
@davsclaus  please see my comments from issue #6 on why this has changed.

The completion logic gonna change a bit with the new improved functionality and bug fixes. With version 0.3.5 we didn't have to add "?" or "&" to get the completion list for the endpoint URI when press ctrl + enter. This had a number of side effects when the cursor was in the middle of a optionor value it could not resolve it and insert / replace it correctly.

This will change so you will have to add "?" or "&" and ctrl + enter to activate the completion list, this is similar to the way the Java completion works

The reason is the way smart completion work with pre search and in replacement of options / values it's too hard to determine what the intention of the user is at this point. Does they press ctrl-space to get a list of possible values or do they want a list of possible options

In the example below the option "exchangePattern" has an unresolved value, and if you place the cursor at the end of the line it should resolve the rest of the value list contains "Ro".

timer:trigger?repeatCount=0&exchangePattern=Ro<cursor>

**Comment by davsclaus** [comment]
Yeah but I am not talking about all of that. I am talking about the cursor at the end of the line, so you can quickly and easily add new options when creating endpoints.

This is a feature I want. Its only when the cursor is at the end of the line.

**Comment by davsclaus** [comment]
This use case will be much more the usual use case. You dont have trailing values having like a `exchangePattern=Ro`. And if you want to edit those options put the cursor after the `=` sign.

Also we can add an [x] in preference so people can turn it off (but they should not, because its so much nicer and faster to just press ctrl + space and build your endpoints without mocking with `?` and `&` and when people forget about XML have to use the longer `&amp;`

**Comment by fharms** [comment]
fine, but just be aware of that you exclude the options to type a head and the press + ctrl to limit your choices or even to automatic complete the options or value.

**Comment by fharms** [comment]
Maybe is possible to do this in the insertHandler, adding a trail & or &amp; like I do with the "=" in some cases

**Comment by davsclaus** [comment]
Yeah when adding a new option we need to add that trailing `&` or `&amp;` automatic. And for values then add `=`.

**Comment by davsclaus** [comment]
I would have to prioritize my book so wont have so much spare time to have fun hacking on this until I get the final chapter for the book complete.

**Comment by fharms** [comment]
can we close this @davsclaus ?

**Comment by davsclaus** [comment]
Oh we are almost there. The `&` should should not be inserted at the end after you have selected an option. Instead we should automatic insert the `&` at the beginning, eg

Today when you have cursor at 
            from("timer:trigger?daemon=true&<caret>")

And press ctrl + space and select something such as `bridgeErrorHandler` you have

        from("timer:trigger?daemon=true&bridgeErrorHandler=true&<caret>")

The `&` is added to the end, what we should do is

        from("timer:trigger?daemon=true&bridgeErrorHandler=true<caret>")

And then if you press ctrl + space, then the plugin knows that because the cursor is at the end of the line, its a new option (because previous character is not the `=` sign etc)

So that when you are done selecting an option and possible its value then there is no trailing `&` sign.

**Comment by davsclaus** [comment]
Almost there only the little annoyance of the `&` is added at the end, instead of the beginning when you add new option.
