### ISSUE TITLE
Wording in error message

### ISSUE THREAD

**Issue by tbsalling** [camel-tooling/camel-idea-plugin#431]
Today I came across this warning from the Camel plugin:

> Camel IDEA plugin cannot download camel-catalog with version 2.20.2. Will fallback and use version 2.21.0

Isn't that more like "fall forward" :-) ?

**Comment by fharms** [comment]
ha ha yes that's seems a little wrong. 

Had you specific setup to download 2.20.2?

**Comment by tbsalling** [comment]
Just this line in build.gradle:

`compile group: 'org.apache.camel', name: 'camel-core', version: "${camelVersion}"
`

**Comment by davsclaus** [comment]
Yes that is by design, that the plugin will use the exact same version as in your pom.xml when possible. We can of course change the word `fallback` to something else. You are welcome to provide a PR. You can even just edit the word directly in github web UI and create a PR that way.

https://github.com/camel-tooling/camel-idea-plugin/blob/master/camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java#L326

**Comment by tbsalling** [comment]
Ok, thanks. I'll close this issue; and instead provide a simple PR later, if I get around to it.
