### ISSUE TITLE
Property placeholder completion only works if the property file is in the same maven module

### ISSUE THREAD

**Issue by rastislavpapp** [camel-tooling/camel-idea-plugin#467]
Hello,

I am part of a team that develops apps for JBoss Fuse with Camel / Blueprint. Our common maven project structure looks like this:
- root 
  - osgi-bundle-1
  - osgi-bundle-2
  - osgi-bundle-3
  - ...
  - profile

The 'profile' module contains a JBoss Fuse profile, which basically builds a zip file with which to deploy all our projects osgi bundles. It also contains property files. 
This way the property placeholder completion support of Camel Idea Plugin does not work, because the property files are actually in a different module. When I move them to the module I'm currently editing, it starts working.

I would actually like to try contributing to this project (never done that before, so I might need some guidance :-) ), I've got the environment all set up, and this might be the first issue I would like to tackle with. If that is OK with you, and I am correct that this in fact is an issue, not user error. Which it very well might be, maybe there is an option in the settings for this that I'm not seeing, or there is a way to do this without changing the code. 
If there are some reasons why this must not work as we need it in our project (e.g. for multi-module projects it could be intended to only see the properties from a file which is in the same module), or there is a specific way you would like to implement it (e.g. as an option in the project settings that just allows you to see code completion items from property files from the whole project, or maybe something like for each of the projects modules you could which other module/modules may contain its properties files.

Further feedback from you will be greatly appreciated, thank you.

**Comment by fharms** [comment]
HI,

Contributions are very welcome.

As I remember it's by design we scan for all properties for the complete project, and we only look for YAML and properties files in the project to limit the number of results.

I don't know enough about Blueprint, but my concern is when we start to scan artifacts for properties files we will present the user with too much information, and they will have hard time finding the properties.

Will it be possible to limit it to only scan artifacts with a specific naming pattern eg. osgi-bundle ?

**Comment by fharms** [comment]
@davsclauswhat what do you think ?

**Comment by davsclaus** [comment]
Yeah I think we should stick to one project mode
