### ISSUE TITLE
Support IDEA 2019.2

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#512]
When updating IDEA it comes with this warning

**Comment by davsclaus** [comment]
![Screenshot 2019-07-24 at 17 47 52](https://user-images.githubusercontent.com/477100/61808222-45de2280-ae3b-11e9-9565-22c85170db78.png)

**Comment by fharms** [comment]
It's default for the gradle plugin to automatic update version and version since build, it can be overridden if we want. But we need to make sure it is actually compatible with older versions. 

> One of the most important is the version. By default, if you modify the version in 
 your build script, the Gradle plugin will automatically update the <version> in your plugin.xml file.
The Gradle plugin will also update the <idea-version since-build=.../> values within the plugin.xml file to match the intellij.version, valid until the last release in the current major version, however you can disable this feature by setting the intellij.updateSinceUntilBuild option to false.

**Comment by fharms** [comment]
I will prefer we stick to the way the gradle plugin do, and it will warn the user if it is incompatible with the current version of IDEA, rather we set the property updateSinceUntilBuild to false and they download the plug-in that might not work with the current version without any warnings.

As I understand you can still install it?

**Comment by davsclaus** [comment]
I dont know I have not upgraded IDEA yet

**Comment by fharms** [comment]
But can you use the new plugin version with your IDEA?

**Comment by davsclaus** [comment]
Yes the new release works with my 2019.1 IDEA

**Comment by rastislavpapp** [comment]
Just checking the progress here - I've got 2019.2 and there is no option to install the newest version of the plugin - it only offers 0.5.6.

**Comment by mikadev** [comment]
I have upgraded to latest version and the plugin is not compatible

**Comment by fharms** [comment]
close #516
