### ISSUE TITLE
Debugger - Can we automatic add camel-debug to classpath if not present

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#652]

**Comment by javaduke** [comment]
I did a log of research, and so far it looks like it is extremely difficult if not impossible, due to the variety of ways Camel can run. Adding a JAR to the module libraries is not enough, because the application can be run by Maven or SpringBoot and it would ignore the module classpath completely. So I think the best we can do is to display a warning if the `camel-debug` is not in the classpath.

**Comment by davsclaus** [comment]
Okay thanks for researching
